export type Params = {
  dayLengthMs: number
  foodLifetimeDays: number
  starvationGraceDays: number
  midnightMealWindowDays: number
  hungerThresholdDays: number
  reproduceChanceCap: number
  reproductionWeightThresholdG: number
  reproductionAgeScaleDays: number
  babySpawnJitterPx: number
  carnivoreMutationChance: number
  carnivoreKillRadius: number
  predationWeightGainFraction: number
  foodPickupRadius: number
  minFoodSeparation: number
  maxSpeedNormal: number
  maxSpeedCarnivoreMultiplier: number
  flakeSeekAcceleration: number
  socialSteerAcceleration: number
  boidNeighborRadius: number
  boidSeparationWeight: number
  boidAlignmentWeight: number
  boidCohesionWeight: number
  huntPerception: number
  fleePerception: number
  wanderStrength: number
  deadFishLingerDays: number
  deadSinkSpeed: number
  skeletonSinkSpeed: number
  skeletonLifetimeDays: number
  aquariumWidth: number
  aquariumHeight: number
}

export const defaultParams: Params = {
  dayLengthMs: 6_500,
  foodLifetimeDays: 0.5,
  starvationGraceDays: 0,
  midnightMealWindowDays: 1.5,
  hungerThresholdDays: 1,
  reproduceChanceCap: 0.25,
  reproductionWeightThresholdG: 300,
  reproductionAgeScaleDays: 100,
  babySpawnJitterPx: 36,
  carnivoreMutationChance: 0.01,
  carnivoreKillRadius: 16,
  predationWeightGainFraction: 0.1,
  foodPickupRadius: 14,
  minFoodSeparation: 28,
  maxSpeedNormal: 88,
  maxSpeedCarnivoreMultiplier: 1.2,
  flakeSeekAcceleration: 5.5,
  socialSteerAcceleration: 4.2,
  boidNeighborRadius: 140,
  boidSeparationWeight: 2.2,
  boidAlignmentWeight: 1.0,
  boidCohesionWeight: 0.85,
  huntPerception: 260,
  fleePerception: 200,
  wanderStrength: 38,
  deadFishLingerDays: 10,
  deadSinkSpeed: 42,
  skeletonSinkSpeed: 38,
  skeletonLifetimeDays: 2,
  aquariumWidth: 800,
  aquariumHeight: 500,
}
